[package]
name = "networkitbgen"
version = "0.1.0"
authors = ["Fabian A.J. Thiele <fabian.thiele@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
